// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl_2TsG9X7b55UJqTy3dpi_8z6-DsKGrk',
    appId: '1:692750707144:web:3abe02fbb4a3134a5578fd',
    messagingSenderId: '692750707144',
    projectId: 'luka-a2f04',
    authDomain: 'luka-a2f04.firebaseapp.com',
    databaseURL: 'https://luka-a2f04-default-rtdb.firebaseio.com',
    storageBucket: 'luka-a2f04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWeYCpIfbrg-5KgSC2rNqz6R45lNkHVPo',
    appId: '1:692750707144:android:94ac51123be81b1b5578fd',
    messagingSenderId: '692750707144',
    projectId: 'luka-a2f04',
    databaseURL: 'https://luka-a2f04-default-rtdb.firebaseio.com',
    storageBucket: 'luka-a2f04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEmrhPcjMtW_p7HMU_2aGHMLVUCDQcNDc',
    appId: '1:692750707144:ios:6ac1784320be64755578fd',
    messagingSenderId: '692750707144',
    projectId: 'luka-a2f04',
    databaseURL: 'https://luka-a2f04-default-rtdb.firebaseio.com',
    storageBucket: 'luka-a2f04.appspot.com',
    iosClientId: '692750707144-j8d48lllehftvfohg9q93jklvrp6njnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.lukaRobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEmrhPcjMtW_p7HMU_2aGHMLVUCDQcNDc',
    appId: '1:692750707144:ios:6ac1784320be64755578fd',
    messagingSenderId: '692750707144',
    projectId: 'luka-a2f04',
    databaseURL: 'https://luka-a2f04-default-rtdb.firebaseio.com',
    storageBucket: 'luka-a2f04.appspot.com',
    iosClientId: '692750707144-j8d48lllehftvfohg9q93jklvrp6njnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.lukaRobot',
  );
}
